export const ADD_TODO_SUCCESS = 'ADD_TODO_SUCCESS';
export const ADD_TODO_ERROR = 'ADD_TODO_ERROR';
export const ADD_TODO_REQUEST = 'ADD_TODO_REQUEST';
export const ADD_TODO_CLEAR = 'ADD_TODO_CLEAR';

export const REMOVE_TODO_SUCCESS = 'REMOVE_TODO_SUCCESS';
export const REMOVE_TODO_ERROR = 'REMOVE_TODO_ERROR';
export const REMOVE_TODO_REQUEST = 'REMOVE_TODO_REQUEST';

export const GET_TODOS = 'GET_TODOS';
